// react/src/lib/components/LanguageModal.tsx
import React, { useState, useMemo } from 'react';
import { Modal } from './Modal';
import { LanguageIcon } from '../icons';
import type { LanguageCode } from '../types';
import type { DisplayLanguage } from '../language-selector';
import { filterLanguages } from '../language-selector';
import { SearchInput } from './SearchInput';
import { LanguageOption } from './LanguageOption';
import { SelectedLanguageDisplay } from './SelectedLanguageDisplay';
import styles from './LanguageModal.module.css';

interface LanguageModalProps {
  displayLanguages: DisplayLanguage[];
  flags?: Record<string, string>;
  isLoading?: boolean;
  error?: Error | null;
  skeletonCount?: number;
  selectedEntry?: DisplayLanguage | null;
  isOpen: boolean;
  showEnglishName?: boolean;
  showFlags?: boolean;
  selectLanguage: (code: LanguageCode) => void;
  close: () => void;
}

export const LanguageModal: React.FC<LanguageModalProps> = ({
  displayLanguages = [],
  flags,
  isLoading = false,
  error = null,
  skeletonCount = 0,
  selectedEntry = null,
  isOpen,
  showEnglishName = true,
  showFlags = false,
  selectLanguage,
  close,
}) => {
  const [searchTerm, setSearchTerm] = useState('');

  const handleClose = () => {
    close();
    setSearchTerm('');
  };

  const handleSelect = (code: LanguageCode) => {
    selectLanguage(code);
    handleClose();
  };

  const filteredLanguages = useMemo(
    () => filterLanguages(displayLanguages, searchTerm),
    [displayLanguages, searchTerm]
  );

  if (!isOpen) return null;

  return (
    <Modal close={handleClose} xbutton bgCloses>
      <div className={styles.container}>
        <header className={styles.header}>
          <LanguageIcon width="20" height="20" />
          <span>Select a Language</span>
        </header>

        {error ? (
          <div className={styles.error}>
            <p>Failed to load languages</p>
            <p className={styles.errorDetails}>{error.message}</p>
          </div>
        ) : (
          <div className={styles.content}>
            {isLoading && (
              <div className={styles.loadingOverlay}>
                <div className={styles.spinner} />
              </div>
            )}

            {selectedEntry && (
              <>
                <SelectedLanguageDisplay
                  language={selectedEntry}
                  flags={flags}
                  showFlags={showFlags}
                  showEnglishName={
                    showEnglishName &&
                    !!selectedEntry.endonym &&
                    selectedEntry.endonym !== selectedEntry.name
                  }
                />
                <hr className={styles.divider} />
              </>
            )}

            <SearchInput value={searchTerm} onChange={setSearchTerm} />

            <div className={styles.list}>
              {displayLanguages.length > 0
                ? filteredLanguages.map((language) => (
                    <LanguageOption
                      key={language.code}
                      language={language}
                      flags={flags}
                      showFlags={showFlags}
                      showEnglishName={
                        showEnglishName &&
                        !!language.endonym &&
                        language.endonym !== language.name
                      }
                      selected={selectedEntry?.code === language.code}
                      onClick={() => handleSelect(language.code)}
                    />
                  ))
                : Array.from({ length: skeletonCount }).map((_, i) => (
                    <div key={i} className={styles.placeholder} />
                  ))}
            </div>
          </div>
        )}
      </div>
    </Modal>
  );
};

// svelte/src/lib/components/LanguageModal.svelte
<script lang="ts">
	import Modal from './Modal.svelte';
	import LanguageIcon from '$lib/icons/LanguageIcon.svelte';
	import type { LanguageCode } from '../types.ts';
	import type { DisplayLanguage } from '../language-selector.ts';
	import { filterLanguages } from '../language-selector.ts';
	import SearchInput from './SearchInput.svelte';
	import LanguageOption from './LanguageOption.svelte';
	import SelectedLanguageDisplay from './SelectedLanguageDisplay.svelte';

	let {
		displayLanguages = [],
		flags,
		isLoading = false,
		error = null,
		skeletonCount = 0,
		selectedEntry = null,
		isOpen = $bindable(false),
		showEnglishName = true,
		showFlags = false,
		selectLanguage,
		close
	}: {
		displayLanguages: DisplayLanguage[];
		flags?: Record<string, string>;
		isLoading?: boolean;
		error?: Error | null;
		skeletonCount?: number;
		selectedEntry?: DisplayLanguage | null;
		isOpen?: boolean;
		showEnglishName?: boolean;
		showFlags?: boolean;
		selectLanguage: (code: LanguageCode) => void;
		close: () => void;
	} = $props();

	let searchTerm = $state('');

	function handleClose() {
		close();
		searchTerm = '';
	}

	function handleSelect(code: LanguageCode) {
		selectLanguage(code);
		handleClose();
	}

	let filteredLanguages = $derived(filterLanguages(displayLanguages, searchTerm));
</script>

{#if isOpen}
	<Modal close={handleClose} xbutton={true} bgCloses={true}>
		<div class="ls-container">
			<header class="ls-header">
				<LanguageIcon width="20" height="20" />
				<span>Select a Language</span>
			</header>

			{#if error}
				<div class="ls-error">
					<p>Failed to load languages</p>
					<p class="ls-error-details">{error.message}</p>
				</div>
			{:else}
				<div class="ls-content">
					{#if isLoading}
						<div class="ls-loading-overlay">
							<div class="ls-spinner"></div>
						</div>
					{/if}

					{#if selectedEntry}
						<SelectedLanguageDisplay
							language={selectedEntry}
							{flags}
							{showFlags}
							showEnglishName={showEnglishName && !!selectedEntry.endonym && selectedEntry.endonym !== selectedEntry.name}
						/>
						<hr />
					{/if}

					<SearchInput bind:value={searchTerm} />

					<div class="ls-list">
						{#if displayLanguages.length > 0}
							{#each filteredLanguages as language (language.code)}
								<LanguageOption
									{language}
									{flags}
									{showFlags}
									showEnglishName={showEnglishName && !!language.endonym && language.endonym !== language.name}
									selected={selectedEntry?.code === language.code}
									onclick={() => handleSelect(language.code)}
								/>
							{/each}
						{:else}
							{#each Array(skeletonCount) as _, i (i)}
								<div class="ls-option-placeholder"></div>
							{/each}
						{/if}
					</div>
				</div>
			{/if}
		</div>
	</Modal>
{/if}

<style>
	hr {
		width: 100%;
		border: none;
		outline: none;
		height: 1px;
		background-color: var(--ls-border);
		margin-top: 0.5rem;
		margin-bottom: 1rem;
	}

	.ls-container {
		display: flex;
		flex-direction: column;
	}

	.ls-content {
		position: relative;
	}

	.ls-loading-overlay {
		position: absolute;
		inset: 0;
		display: flex;
		align-items: center;
		justify-content: center;
		background: color-mix(in srgb, var(--ls-modal-bg) 70%, transparent);
		z-index: 10;
		opacity: 0;
		animation: ls-fade-in 0.3s ease-out 0.15s forwards;
	}

	@keyframes ls-fade-in {
		to { opacity: 1; }
	}

	.ls-spinner {
		width: 32px;
		height: 32px;
		border: 3px solid var(--ls-border);
		border-top-color: var(--ls-fg);
		border-radius: 50%;
		animation: ls-spin 0.8s linear infinite;
	}

	@keyframes ls-spin {
		to { transform: rotate(360deg); }
	}

	.ls-error {
		display: flex;
		flex-direction: column;
		align-items: center;
		gap: 1rem;
		padding: 2rem 1rem;
		color: var(--ls-fg-muted);
	}

	.ls-header {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: 0.5rem;
		font-size: 1.125rem;
		color: var(--ls-fg);
		margin-bottom: 1rem;
	}

	.ls-list {
		display: flex;
		flex-wrap: wrap;
		justify-content: center;
		gap: 0.5rem 1rem;
		scrollbar-color: var(--ls-border) transparent;
	}

	.ls-option-placeholder {
		padding: var(--ls-padding);
		background: var(--ls-bg);
		border: 1px solid var(--ls-border);
		border-radius: var(--ls-radius);
		width: 100%;
		max-width: 360px;
		height: 58px;
	}
</style>
