// react/src/lib/components/LanguageSelectorStatic.tsx
import React, { useMemo } from 'react';
import type { DisplayOptions } from '../types';
import { loadDataFromFile } from '../language-file';
import { LanguageSelectorHandler } from './LanguageSelectorHandler';

interface LanguageSelectorStaticProps {
  staticFileData: string | object;
  selectedLanguage?: string | null;
  onSelectedLanguageChange?: (language: string | null) => void;
  onSelection?: (language: string) => void;
  displayOptions?: DisplayOptions;
}

export const LanguageSelectorStatic: React.FC<LanguageSelectorStaticProps> = ({
  staticFileData,
  selectedLanguage,
  onSelectedLanguageChange,
  onSelection,
  displayOptions: propsDisplayOptions,
}) => {
  const { data: staticData, displayOptions: staticDisplayOptions } = useMemo(
    () => loadDataFromFile(staticFileData),
    [staticFileData]
  );

  return (
    <LanguageSelectorHandler
      staticData={staticData}
      displayOptions={propsDisplayOptions ?? staticDisplayOptions ?? undefined}
      selectedLanguage={selectedLanguage}
      onSelectedLanguageChange={onSelectedLanguageChange}
      onSelection={onSelection}
    />
  );
};

// svelte/src/lib/components/LanguageSelectorStatic.svelte
<script lang="ts">
	import type { DisplayOptions } from '../types.ts';
	import { loadDataFromFile } from '../language-file.ts';
	import LanguageSelectorHandler from './LanguageSelectorHandler.svelte';

	let {
		staticFileData,
		selectedLanguage = $bindable<string | null>(null),
		onSelection = () => {},
		displayOptions
	}: {
		staticFileData: string | object;
		selectedLanguage?: string | null;
		onSelection?: (language: string) => void;
		displayOptions?: DisplayOptions;
	} = $props();

	const { data:staticData, displayOptions:staticDisplayOptions } = loadDataFromFile(staticFileData);

</script>

<LanguageSelectorHandler
	bind:selectedLanguage
	{onSelection}
	{staticData}
	displayOptions={displayOptions ?? staticDisplayOptions ?? undefined}
/>
