// react/src/lib/components/LanguageSelector.tsx
import React from 'react';
import type { LanguageCode, DisplayOptions, LoadOptions } from '../types';
import { LanguageSelectorHandler } from './LanguageSelectorHandler';

interface LanguageSelectorProps {
  languages: string[];
  displayOptions?: DisplayOptions;
  loadOptions?: LoadOptions;
  selectedLanguage?: LanguageCode | null;
  onSelectedLanguageChange?: (language: LanguageCode | null) => void;
  onSelection?: (language: LanguageCode) => void;
}

export const LanguageSelector: React.FC<LanguageSelectorProps> = ({
  languages,
  displayOptions = {},
  loadOptions = {},
  selectedLanguage,
  onSelectedLanguageChange,
  onSelection,
}) => {
  if (!languages || languages.length === 0) {
    console.error('[LanguageSelector] No languages provided.');
    return null;
  }

  return (
    <LanguageSelectorHandler
      languages={languages}
      displayOptions={displayOptions}
      loadOptions={loadOptions}
      selectedLanguage={selectedLanguage}
      onSelectedLanguageChange={onSelectedLanguageChange}
      onSelection={onSelection}
    />
  );
};

// svelte/src/lib/components/LanguageSelector.svelte
<script lang="ts">
	import type { LanguageCode, DisplayOptions, LoadOptions } from '../types.ts';
	import LanguageSelectorHandler from './LanguageSelectorHandler.svelte';
	let {
		languages,
		displayOptions = {},
		loadOptions = {},
		selectedLanguage = $bindable<LanguageCode | null>(null),
		onSelection = () => {}
	}: {
		languages: string[];
		displayOptions?: DisplayOptions;
		loadOptions?: LoadOptions;
		selectedLanguage?: LanguageCode | null;
		onSelection?: (language: LanguageCode) => void;
	} = $props();

</script>

{#if languages && languages.length > 0}
		<LanguageSelectorHandler
			bind:selectedLanguage
			{onSelection}
			{languages}
			{displayOptions}
			{loadOptions}
		/>
{:else}
	{console.error('[LanguageSelectorEmbed] No languages provided.')}
{/if}
